name: build lambda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true


      
      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-cache

      - name: Release lambda
        run: |
          pip install cargo-lambda
          OPENSSL_DIR=/usr cargo lambda build --release
          ls -R target/lambda/
          cargo lambda deploy --binary-path target/lambda/stockalerts/bootstrap --iam-role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/stockRole
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
